config/routes.rb
Rails.application.routes.draw do
  root to: 'admin#index'

  get '/signin', to: 'users#sign_in'
  post '/signin', to: 'users#sign_in!'
  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#sign_up!'
  get '/signout', to: 'users#signout'

  get '/cemp', to: 'users#check_empid'
  
  get '/careers', to: 'admin#view_all_career'
  get '/nc', to: 'admin#add_new_career'
  post '/create_career', to: 'admin#create_new_career'

  get '/ec/:id(.:format)', to: 'admin#edit_career'
  post '/uc/:id(.:format)', to: 'admin#update_career'
  get '/dc/:id(.:format)', to: 'admin#delete_career'

  get '/emps', to: 'admin#view_all_employees'
  get '/nemp', to: 'admin#new_employee'
  post '/newemp', to: 'admin#create_new_employee'
  get '/nepd/:id(.:format)', to: 'admin#emp_profile'
  post '/cepd/:id(.:format)', to: 'admin#create_employee_profile', as: 'create_emp_detail'
  get '/eepd/:id(.:format)', to: 'admin#edit_employee'
  post '/uepd/:id(.:format)', to: 'admin#update_employee_profile', as: 'update_emp_detail'
  get '/ve/:id(.:format)', to: 'admin#view_employee'
  get '/delemp', to: 'admin#delete_employee'
  get '/accdeact', to: 'admin#deactive_employee'
  get '/checkcont', to: 'admin#check_contact'
  get '/edu_qualify', to: 'admin#geteduaction'
  get '/check_pass', to: 'admin#check_password'
  get '/empws/:id', to: 'admin#employee_workstatus'

  get '/employee', to: 'employees#index'
  get '/accsts', to: 'employees#emp_account_status'
  get '/emp_pro', to: 'employees#emp_profile'
  get '/emp_log', to: 'employees#emp_log_details'

  get '/find_state', to: 'employees#state_list'
  get '/find_district', to: 'employees#district_list'
  get '/find_taluk', to: 'employees#taluk_list'
  get '/find_pincode', to: 'employees#pincode_list'
  get '/find_village', to: 'employees#village_list'
  get '/find_subcat', to: 'employees#subcatgory_list'
  get '/emp_data', to: 'employees#view_saved_file'
  get '/file/:id', to: 'employees#download_file'

  post '/add_addr', to: 'employees#create_new_address_text', as: 'addresstext'
  post '/add_rows', to: 'employees#create_new_address_rows', as: 'addressrows'
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_cache_buster

  require 'fileutils'
  require 'socket'
  include EmployeesHelper

  def index
  	@countries = CountryMaster.all.order('country_name asc')
    @maincats = CategoryMaster.where(:parent_id=>0).order('cat_name asc')
    @address = AddressMaster.new
  end

  def state_list
    @states = StateMaster.where(:country_id => params[:country]).order('state_name asc')
    respond_to do |format|
      format.html 
      format.json { render json: @states }
    end
  end

  def district_list
    @districts = DistrictMaster.where(:state_id => params[:state]).order('district_name asc')
    respond_to do |format|
      format.html 
      format.json { render json: @districts }
    end
  end

  def taluk_list
    @taluks = TalukMaster.where(:district_id => params[:district]).order('taluk_name asc')
    respond_to do |format|
      format.html 
      format.json { render json: @taluks }
    end
  end

  def pincode_list
    @codes = PincodeMaster.where(:taluk_id => params[:taluk]).order('pincode asc')
    respond_to do |format|
      format.html 
      format.json { render json: @codes }
    end
  end

  def village_list
    @village = VillageMaster.where(:pincode_id => params[:pin], :taluk_id => params[:talid]).order('village_name asc')
    respond_to do |format|
      format.html 
      format.json { render json: @village }
    end
  end

  def subcatgory_list
    @subcat = CategoryMaster.where(:parent_id=>params[:catid]).order('cat_name asc')
    respond_to do |format|
      format.html
      format.json{render json:@subcat }
    end
  end

  def create_new_address_text
    @checkarea = VillageMaster.where(:country_id=>params[:country], :state_id=>params[:state], :district_id=>params[:district], :taluk_id=>params[:taluk], :pincode_id=>params[:pincode], :id=>params[:village])
    if @checkarea.count != 0
      check = 1
    else
      check = 0
    end

    if check == 1
      empid = session[:user]['empid']
      date = Date.today.strftime('%d_%m_%Y')
      country = CountryMaster.find(params[:country]).country_name
      state = StateMaster.find(params[:state]).state_name
      district = DistrictMaster.find(params[:district]).district_name
      taluk = TalukMaster.find(params[:taluk]).taluk_name
      pincode = PincodeMaster.find(params[:pincode]).pincode
      village = VillageMaster.find(params[:village]).village_name
      maincat = CategoryMaster.find(params[:maincat]).cat_name
      if params[:subcat]
        subcat = CategoryMaster.find(params[:subcat]).cat_name
        @filedir = "#{Rails.root}/storage/#{empid}/#{date}/#{country}/#{state}/#{district}/#{taluk}/#{pincode}/#{village}/#{maincat}/#{subcat}"
      else
        @filedir = "#{Rails.root}/storage/#{empid}/#{date}/#{country}/#{state}/#{district}/#{taluk}/#{pincode}/#{village}/#{maincat}"
      end
      if Dir.exists?(@filedir)
        @getcount = Dir["#{@filedir}/*.txt"]
        @filename = "#{village}.txt"
        @pagecount = @getcount.size
        exist = 1
      else
        maindir = FileUtils.mkdir_p(@filedir)
        @filename = "#{village}.txt"
        @pagecount = 1
        exist = 0
      end

      @file = File.new("#{@filedir}/#{@filename}", "a")
      if @file
        @file.syswrite("#{params[:address]}\n")
      else
        flash[:error] = 'Unable to open file'
      end

      if exist == 0
        newpath = EmpFilepath.new()
      else
        newpath = EmpFilepath.find_by(file_name:@filename)
      end
      newpath.empid = session[:user]['empid']
      newpath.logid = session[:logid]
      newpath.file_path = File.dirname(@file)
      newpath.file_name = File.basename(@file)
      newpath.create_date = Date.today
      if newpath.save
        filename = "#{newpath.file_path}/#{newpath.file_name}"
        linecount = `wc -l "#{filename}"`.strip.split(' ')[0].to_i
        
        @exist = EmpWorksheetCount.where(empid: session[:user]['empid'], logid:session[:logid], fileid: newpath.id, create_at: Date.today).pluck(:id)
        if !@exist.empty?
          workcount = EmpWorksheetCount.where(id: @exist).last
        else
          workcount = EmpWorksheetCount.new
        end
        workcount.empid = session[:user]['empid']
        workcount.fileid = newpath.id
        workcount.catid = params[:maincat]
        workcount.logid = session[:logid]
        workcount.line_count = linecount
        workcount.page_count = @pagecount
        workcount.create_at = Date.today
        workcount.save

        flash[:success] = 'Data has been saved successfully'
        redirect_to '/employee'
      else
      end
    end
  end

  def create_new_address_rows
    @error = []
    if params[:name_1]
      address_1(params[:name_1], params[:address_1], params[:phone_1], params[:website_1], params[:landmark_1], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_2]
      address_1(params[:name_2], params[:address_2], params[:phone_2], params[:website_2], params[:landmark_2], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_3]
      address_1(params[:name_3], params[:address_3], params[:phone_3], params[:website_3], params[:landmark_3], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_4]
      address_1(params[:name_4], params[:address_4], params[:phone_4], params[:website_4], params[:landmark_4], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_5]
      address_1(params[:name_5], params[:address_5], params[:phone_5], params[:website_5], params[:landmark_5], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_6]
      address_1(params[:name_6], params[:address_6], params[:phone_6], params[:website_6], params[:landmark_6], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_7]
      address_1(params[:name_7], params[:address_7], params[:phone_7], params[:website_7], params[:landmark_7], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_8]
      address_1(params[:name_8], params[:address_8], params[:phone_8], params[:website_8], params[:landmark_8], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_9]
      address_1(params[:name_9], params[:address_9], params[:phone_9], params[:website_9], params[:landmark_9], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end

    if params[:name_10]
      address_1(params[:name_10], params[:address_10], params[:phone_10], params[:website_10], params[:landmark_10], session[:user]['empid'], params[:pincode])
      @error.push(@address_1)
    end
    
    if @error.size != 0
      flash[:error] = "#{@error.join(', ')} are already exists"
    else
      flash[:success] = "Data are saved successfully"
    end
    redirect_to '/employee'
  end

  def emp_profile
  	@emp = EmployeeProfile.find_by(:userid=>session[:user]["id"])
  	@empq = QualificationMaster.find(@emp.qualification).name
  	@empd = DepartmentMaster.find(@emp.department).name
  end

  def view_saved_file
    @files = EmpFilepath.where(empid: session[:user]['empid'])
  end

  def download_file
    @file = EmpFilepath.find(params[:id])
    @location = @file.file_path + "/" + @file.file_name

    response.headers.delete("Pragma")
    response.headers.delete('Cache-Control')

    send_file(@location,
      :filename     => @file.file_name,
      :disposition  =>  'attachment',
      :streaming    =>  'true',
      :type         =>  'application/octet-stream'
    )
  end

  def emp_log_details
  end

  def emp_account_status
  	@user = User.find(session[:user]["id"])
  end

  def set_cache_buster
     response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
     response.headers["Pragma"] = "no-cache"
     response.headers["Expires"] = "0"
   end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def address_1(name, address, phone, website, landmark, empid, pincode)
		@exist1 = AddressMaster.where(name: name, pincode: pincode)
		if @exist1.count == 0
			new_address(name, address, phone, website, landmark, empid, pincode)
		else
			return @address_1 = name
		end
	end

	def new_address(name, address, phone, website, landmark, empid, pincode)
		new_address = AddressMaster.new()
		new_address.empid = empid
		new_address.create_date = Date.today
		new_address.name = name
		new_address.address = address
		new_address.landmark = landmark
		new_address.phone_no = phone
		new_address.website = website
		new_address.pincode = pincode
		new_address.save
	end
end

app/views/employees/_category_list.html.erb
<div class="col">
	<div class="form-group">
		<select class="form-control category" name="maincat">
			<option value="0">Select Category...</option>
			<% @maincats.each do |c| %>
				<option value="<%= c.id %>"><%= c.cat_name %></option>
			<% end %>
		</select>
	</div>
</div>

app/views/employees/_country_list.html.erb
<div class="col">
	<div class="form-group">
    <select class="country form-control" name="country">
      <option value="0">Select Country...</option>
      <% @countries.each do |country| %>
        <option value="<%= country.id %>"><%= country.country_name %></option>
      <% end %>
    </select>
  </div>
</div>

app/views/employees/_district_list.html.erb
<div class="col">
	<div class="form-group">
    <select class="form-control district" name="district">
      <option value="0">Select District...</option>
    </select>
  </div>
</div>

app/views/employees/_excelformat.html.erb
<%= form_tag addressrows_path do %>
	<div class="card">
		<div class="row">
			<div class="col">
				<%= render 'country_list' %>
			</div>
			<div class="col">
				<%= render 'state_list' %>
			</div>
			<div class="col">
				<%= render 'district_list' %>
			</div>
			<div class="col">
				<%= render 'taluk_list' %>
			</div>
			<div class="col">
				<%= render 'pincode_list' %>
			</div>
			<div class="col">
				<%= render 'village_list' %>
			</div>
		</div>

		<div class="row">
			<div class="col">
				<%= render "category_list" %>
			</div>
			<div class="col">
				<%= render "subcatgory_list" %>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th>Name</th>
								<th>Address</th>
								<th>Phone Number</th>
								<th>Website</th>
								<th>Land mark</th>
							</tr>
						</thead>
						<tbody style="max-height: 300px;">
							<% for i in 1..10 do %>
								<tr>
									<td><input type="text" name="name_<%=i%>" class="form-control caplet" placeholder="Name" required></td>
									<td><input type="text" name="address_<%=i%>" class="form-control" placeholder="Address" required></td>
									<td><input type="text" name="phone_<%=i%>" class="form-control numeric" placeholder="Phone Number" required></td>
									<td><input type="text" name="website_<%=i%>" class="form-control" placeholder="Website" required></td>
									<td><input type="text" name="landmark_<%=i%>" class="form-control" placeholder="Landmark" required></td>
								</tr>
							<%end%>
						</tbody>
					</table>
				</div>								
			</div>
			<div class="col-md-6">
				<div class="form-group">
	        <input type="submit" value="Submit" class="btn btn-app pull-right addform">
	      </div>
				<div style="margin-bottom: 3em;"></div>
			</div>
		</div>
	</div>
<% end %>

app/views/employees/_pincode_list.html.erb
<div class="col">
	<div class="form-group">
    <select class="form-control pincode" name="pincode">
      <option value="0">Select Pincode...</option>
    </select>
  </div>
</div>

app/views/employees/_plaintext.html.erb
<%= form_tag addresstext_path do %>
	<div class="card">
		<div class="row">
			<div class="col">
				<%= render 'country_list' %>
			</div>
			<div class="col">
				<%= render 'state_list' %>
			</div>
			<div class="col">
				<%= render 'district_list' %>
			</div>
			<div class="col">
				<%= render 'taluk_list' %>
			</div>
			<div class="col">
				<%= render 'pincode_list' %>
			</div>
			<div class="col">
				<%= render 'village_list' %>
			</div>
		</div>

		<div class="row">
			<div class="col">
				<%= render "category_list" %>
			</div>
			<div class="col">
				<%= render "subcatgory_list" %>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<textarea name="address" rows="25" class="form-control" id="addressentry" autocomplete="false" required></textarea>
				</div>								
			</div>
			<div class="col-md-6">
				<div class="form-group">
	        <input type="submit" value="Submit" class="btn btn-app pull-right addform">
	      </div>
				<div style="margin-bottom: 3em;"></div>
			</div>
		</div>
	</div>
<% end %>

app/views/employees/_subcatgory_list.html.erb
<div class="form-group">
	<select class="form-control subcat" name="subcat">
		<option value="0">Select Sub-Category...</option>
	</select>
</div>

app/views/employees/_taluk_list.html.erb
<div class="col">
	<div class="form-group">
    <select class="form-control taluk" name="taluk">
      <option value="0">Select Taluk...</option>
    </select>
  </div>
</div>

app/views/employees/_village_list.html.erb
<div class="col">
	<div class="form-group">
    <select class="form-control village" name="village">
      <option value="0">Select Village...</option>
    </select>
  </div>
</div>

app/views/employees/emp_account_status.html.erb
<!DOCTYPE html>
<html>
<head></head>

<body>
	<div class="sidebar">
		<div class="scrollbar-inner sidebar-wrapper">
			<div class="user">
				<div class="photo"><img src="assets/profile.png"></div>
				<div class="info">
					<a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
						<span>
							<%= session[:user]["name"] %>
							<span class="user-level">Employee ID : <%= session[:user]["empid"] %></span>
						</span>
					</a>
					<div class="clearfix"></div>
				</div>
			</div>
			<ul class="nav">
				<li class="nav-item"><a href="/employee"><i class="fa fa-dashboard"></i><p>Dashboard</p></a></li>
				<li class="nav-item active"><a href="/emp_pro"><i class="fa fa-user-o"></i><p>My Profile</p></a></li>
				<li class="nav-item"><a href="/emp_log"><i class="fa fa-table"></i><p>Login Details</p></a></li>
				<li class="nav-item"><a href="#"><i class="fa fa-envelope-o"></i><p>Leave Request</p></a></li>
			</ul>
		</div>
	</div>

	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Employee Accounts</h4>
				<div class="row">
					<div class="col-md-9">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Account Settings</div>
							</div>
							<div class="card-body">
								<table class="table table-hover">
									<tbody>
										<tr>
											<td><label><b>Employee ID</b></label></td>
											<td>:&emsp;<%= @user.empid %></td>
										</tr>
										<tr>
											<td><label><b>Name</b></label></td>
											<td>:&emsp;<%= @user.name %></td>
										</tr>
										<tr>
											<td><label><b>Email</b></label></td>
											<td>:&emsp;<%= @user.email %></td>
										</tr>
										<tr>
											<td><label><b>Phone Number</b></label></td>
											<td>:&emsp;<%= EmployeeProfile.find_by(:userid=>@user.id).phone_no %></td>
										</tr>
										<tr>
											<td><label><b>Account Status</b></label></td>
											<td>:&emsp;<span style="color:green;">Active</span></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/employees/emp_log_details.html.erb
<!DOCTYPE html>
<html>
<head></head>

<body>
	<div class="sidebar">
		<div class="scrollbar-inner sidebar-wrapper">
			<div class="user">
				<div class="photo"><img src="assets/profile.png"></div>
				<div class="info">
					<a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
						<span>
							<%= session[:user]["name"] %>
							<span class="user-level">Employee ID : <%= session[:user]["empid"] %></span>
						</span>
					</a>
					<div class="clearfix"></div>
				</div>
			</div>
			<ul class="nav">
				<li class="nav-item"><a href="/employee"><i class="fa fa-dashboard"></i><p>Dashboard</p></a></li>
				<li class="nav-item"><a href="/emp_pro"><i class="fa fa-user-o"></i><p>My Profile</p></a></li>
				<li class="nav-item active"><a href="/emp_log"><i class="fa fa-table"></i><p>Login Details</p></a></li>
				<li class="nav-item"><a href="#"><i class="fa fa-envelope-o"></i><p>Leave Request</p></a></li>
			</ul>
		</div>
	</div>

	<div class="main-panel">
		
	</div>
</body>
</html>

app/views/employees/emp_profile.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.eprof').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Profile Details</h4>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Employees Personal Details</div>
							</div>
							<div class="card-body">
								<div class="col-md-6 pull-left">
									<div class="form-group">
										<label>Door No</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.door_no %>" disabled>
									</div>
									<div class="form-group">
										<label>Street</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.street %>" disabled>
									</div>
									<div class="form-group">
										<label>Village / Hometown</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.village %>" disabled>
									</div>
									<div class="form-group">
										<label>City</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.city %>" disabled>
									</div>
									<div class="form-group">
										<label>Pincode</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.pincode %>" disabled>
									</div>
									<div class="form-group">
										<label>Experience</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.experience %>" disabled>
									</div>
								</div>

								<div class="col-md-6 pull-right">
									<div class="form-group">
										<label>Educational Qualification</label>
										<input type="text" name="door_no" class="form-control" value="<%= @empq %>" disabled>
									</div>
									<div class="form-group">
										<label>Department</label>
										<input type="text" name="door_no" class="form-control" value="<%= @empd %>" disabled>
									</div>
									<div class="form-group">
										<label>Phone Number</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.phone_no %>" disabled>
									</div>
									<div class="form-group">
										<label>Date of Birth</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.birth_date.strftime('%d-%m-%Y') %>" disabled>
									</div>
									<div class="form-group">
										<label>Bank Account Number</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.bank_acc_no %>" disabled>
									</div>
									<div class="form-group">
										<label>Bank IFSC Code</label>
										<input type="text" name="door_no" class="form-control" value="<%= @emp.bank_ifsc %>" disabled>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.ehome').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<div class="card">
					<div class="row">
						<div class="col-md-3">
							<div class="form-group">
								<select class="form-control" id="entcat" name="entcat">
									<option value="0">Select Entry Category</option>
									<option value="1">Plain Text</option>
									<option value="2">Excel Sheet</option>
									<option value="3">PDF Converter</option>
								</select>
							</div>
						</div>
						<div class="col-md-3 pull-left">
							<div class="form-group">
								<span style="color:#E25336;">* Please select any option to address entry</span>
							</div>
						</div>
					</div>
				</div>

				<div class="partialview">
					<div id="textplain"><%= render 'plaintext' %></div>
					<div id="xlssheet"><%= render 'excelformat' %></div>
				</div>
			</div>
		</div>
	</div>
</body>
<script type="text/javascript">
	$(document).ready(function(){
		$("#textplain").hide();
		$("#xlssheet").hide();
		$('#addform').attr("disabled", true);
	});
</script>
</html>

app/views/employees/view_saved_file.html.erb
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
		tbody {
	    display:block;
	    height:400px;
	    overflow:auto;
		}
		thead, tbody tr {
	    display:table;
	    width:100%;
	    table-layout:fixed;
		}
		thead {
		  width: calc( 100% - 1em )
		}
	</style>

	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.edown').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Stored Files</h4>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<div class="card-title">List of Files</div>
							</div>

							<div class="card-body">
								<table class="table table-hover">
									<thead>
										<tr>
											<th>S.No</th>
											<th>Date</th>
											<th>File Name</th>
											<th>Download</th>
										</tr>
									</thead>

									<%if @files%>
										<tbody>
											<%i = 1%>
											<%@files.each do |f|%>
												<tr>
													<td class="aligncen"><%= i %></td>
													<td class="aligncen"><%= f.create_date.strftime('%d-%m-%Y') %></td>
													<td class="aligncen"><%= f.file_name %></td>
													<td class="aligncen"><a href="/file/<%= f.id %>?empid=<%= session[:user]['empid'] %>"><i class="fa fa-download"></i> </a></td>
												</tr>
												<% i += 1%>
											<%end%>
										</tbody>
									<%else%>
									<%end%>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>