config/routes.rb
Rails.application.routes.draw do
  root to: 'admin#index'

  get '/signin', to: 'users#sign_in'
  post '/signin', to: 'users#sign_in!'
  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#sign_up!'
  get '/signout', to: 'users#signout'

  get '/cemp', to: 'users#check_empid'
  
  get '/careers', to: 'admin#view_all_career'
  get '/nc', to: 'admin#add_new_career'
  post '/create_career', to: 'admin#create_new_career'

  get '/ec/:id(.:format)', to: 'admin#edit_career'
  post '/uc/:id(.:format)', to: 'admin#update_career'
  get '/dc/:id(.:format)', to: 'admin#delete_career'

  get '/emps', to: 'admin#view_all_employees'
  get '/nemp', to: 'admin#new_employee'
  post '/newemp', to: 'admin#create_new_employee'
  get '/nepd/:id(.:format)', to: 'admin#emp_profile'
  post '/cepd/:id(.:format)', to: 'admin#create_employee_profile', as: 'create_emp_detail'
  get '/eepd/:id(.:format)', to: 'admin#edit_employee'
  post '/uepd/:id(.:format)', to: 'admin#update_employee_profile', as: 'update_emp_detail'
  get '/ve/:id(.:format)', to: 'admin#view_employee'
  get '/delemp', to: 'admin#delete_employee'
  get '/accdeact', to: 'admin#deactive_employee'
  get '/checkcont', to: 'admin#check_contact'
  get '/edu_qualify', to: 'admin#geteduaction'
  get '/check_pass', to: 'admin#check_password'
  get '/empws/:id', to: 'admin#employee_workstatus'

  get '/employee', to: 'employees#index'
  get '/accsts', to: 'employees#emp_account_status'
  get '/emp_pro', to: 'employees#emp_profile'
  get '/emp_log', to: 'employees#emp_log_details'

  get '/find_state', to: 'employees#state_list'
  get '/find_district', to: 'employees#district_list'
  get '/find_taluk', to: 'employees#taluk_list'
  get '/find_pincode', to: 'employees#pincode_list'
  get '/find_village', to: 'employees#village_list'
  get '/find_subcat', to: 'employees#subcatgory_list'
  get '/emp_data', to: 'employees#view_saved_file'
  get '/file/:id', to: 'employees#download_file'

  post '/add_addr', to: 'employees#create_new_address_text', as: 'addresstext'
  post '/add_rows', to: 'employees#create_new_address_rows', as: 'addressrows'
end

app/models/address_master.rb
class AddressMaster < ApplicationRecord
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/career_applied.rb
class CareerApplied < ApplicationRecord
end

app/models/category_master.rb
class CategoryMaster < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/country_master.rb
class CountryMaster < ApplicationRecord
end

app/models/district_master.rb
class DistrictMaster < ApplicationRecord
end

app/models/emp_daywise.rb
class EmpDaywise < ApplicationRecord
end

app/models/emp_filepath.rb
class EmpFilepath < ApplicationRecord
end

app/models/emp_loginwise.rb
class EmpLoginwise < ApplicationRecord
end

app/models/emp_monthwise.rb
class EmpMonthwise < ApplicationRecord
end

app/models/login_master.rb
class LoginMaster < ApplicationRecord
end

app/models/pincode_master.rb
class PincodeMaster < ApplicationRecord
end

app/models/state_master.rb
class StateMaster < ApplicationRecord
end

app/models/taluk_master.rb
class TalukMaster < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/models/village_master.rb
class VillageMaster < ApplicationRecord
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_emp_daywise.html.erb
<div class="table-responsive">
	<table class="table table-hover table-bordered">
		<thead>
			<th>S.No</th>
			<th>Date</th>
			<th>Max Hour Per/Day</th>
			<th>Line Count</th>
			<th>Page Count</th>
		</thead>
		
		<% if !@daywise.empty? %>
			<tbody style="max-height: 150px;">
				<% s = 1 %>
				<% @daywise.each do |d| %>
					<tr>
						<td class="aligncen"><%= s %></td>
						<td class="aligncen"><%= d.date.strftime('%d-%m-%Y') %></td>
						<% @gettime = LoginMaster.find_by(log_date: d.date, empid: @user.empid)
							t1 = @gettime.login_time
							t2 = @gettime.logout_time
							t = t2 - t1
						%>
						<td class="aligncen"><%= Time.at(t).utc.strftime("%H:%M:%S") %></td>
						<td class="aligncen"><%= d.line_count %></td>
						<td class="aligncen"><%= d.page_count %></td>
					</tr>
					<% s += 1 %>
				<% end %>
			</tbody>
		<% else %>
			<tbody>
				<tr style="color:#E25336;height:180px;">
					<td colspan="5" class="aligncen">
						<b><i class="fa fa-warning" style="color:#E25336;"></i>&emsp;No Records found!</b>
					</td>
				</tr>
			</tbody>
		<% end %>	
	</table>
</div>

app/views/admin/_emp_loginwise.html.erb
<div class="table-responsive">
	<table class="table table-hover table-bordered">
		<thead>
			<th>S.No</th>
			<th>Date</th>
			<th>Max Hour</th>
			<th>Start Time</th>
			<th>End Time</th>
			<th>Line Count</th>
			<th>Page Count</th>
		</thead>
		
		<% if !@logwise.empty? %>
			<tbody>
				<% s = 1 %>
				<% @logwise.each do |l| %>
					<tr>
						<td class="aligncen"><%= s %></td>
						<td><%= l.date.strftime('%d-%m-%Y') %></td>
						<% tin = l.intime %>
						<%if !l.outtime.nil?%>
							<% tout = l.outtime %>
						<%else%>
							<% tout = Time.now %>
						<%end%>
						<% time = tout - tin %>
						<td class="aligncen">
							<%= Time.at(time).utc.strftime("%H:%M:%S") %>
						</td>
						<td>
							<%= l.intime.strftime('%H:%M:%S') %>
						</td>
						<td>
							<% if !l.outtime.nil? %>
								<%= l.outtime.strftime('%H:%M:%S') %>
							<% else %>
								--
							<% end %>
						</td>
						<% @lcount = EmpWorksheetCount.where(logid: l.id)
						@linearr = []
						@pagearr = []
						@lcount.each do |lc|
							@linearr.push(lc.line_count)
							@pagearr.push(lc.page_count)
						end
						@linesum = @linearr.inject(0){|sum,x| sum + x }
						@pagesum = @pagearr.inject(0){|sum,x| sum + x }%>
						<td class="aligncen">
							<%= @linesum %>
						</td>
						<td class="aligncen">
							<%= @pagesum %>
						</td>
					</tr>
					<% s += 1 %>
				<% end %>
			</tbody>
		<% else %>
			<tbody>
				<tr style="color:#E25336;height:180px;">
					<td colspan="7" class="aligncen">
						<b><i class="fa fa-warning" style="color:#E25336;"></i>&emsp;No Records found!</b>
					</td>
				</tr>
			</tbody>
		<% end %>	
	</table>
</div>

app/views/admin/_emp_monthwise.html.erb
<div class="table-responsive">
	<table class="table table-hover table-bordered">
		<thead>
			<th>S.No</th>
			<th>Month</th>
			<th>Line Count</th>
			<th>Page Count</th>
			<th>Total Cost</th>
		</thead>

		<%if !@monthwise.empty?%>
			<tbody>
				<% s = 1 %>
				<% @monthwise.each do |m| %>
					<tr>
						<td class="aligncen"><%= s %></td>
						<td class="aligncen"><%= m[0].strftime('%B-%Y') %></td>
						<td class="aligncen"><%= m[1][0].line_count %></td>
						<td class="aligncen"><%= m[1][0].page_count %></td>
						<% p = BigDecimal(m[1][0].line_count) %>
						<% cost = p / 4000 %>
						<td class="aligncen"><%=  cost.to_f %></td>
					</tr>
					<%s += 1%>
				<%end%>
			</tbody>
		<%else%>
			<tbody>
				<tr style="color:#E25336;height:180px;">
					<td colspan="7" class="aligncen">
						<b><i class="fa fa-warning" style="color:#E25336;"></i>&emsp;No Records found!</b>
					</td>
				</tr>
			</tbody>
		<%end%>
	</table>
</div>

app/views/admin/_employees_list.html.erb
<table class="table table-hover table-bordered">
	<thead>
		<th>S.No</th>
		<th>Employee ID</th>
		<th>Name</th>
		<th>Email</th>
		<th>Deactive</th>
		<th>Work Status</th>
		<th>Online</th>
		<th>View</th>
		<th>Edit</th>
		<th>Delete</th>
	</thead>

	<% if !@employees.empty? %>
		<tbody id="myTable">
			<% i = 1 %>
			<% @employees.each do |emp| %>
				<% if emp.deactive == 1 %>
					<tr style="color: red;">
				<% else %>
					<tr>
				<% end %>
					<td class="aligncen"><%= i %></td>
					<td class="aligncen"><%= emp.empid %></td>
					<td><%= emp.name %></td>
					<td><%= emp.email %></td>
					<td class="aligncen">
						<% if emp.deactive == 0 %>
							<input type="checkbox" value="active" data-toggle="tooltip" title="Deactive" onclick="deactive(<%= emp.id %>, 1)">
						<% elsif emp.deactive == 1 %>
							<input type="checkbox" value="deactive" data-toggle="tooltip" title="Active" onclick="deactive(<%= emp.id %>, 0)" checked>
						<% end %>
					</td>
					<td class="aligncen">
						<a href="/empws/<%= emp.id %>" data-toggle="tooltip" title="View Work Status"><i class="fa fa-link"></i></a>
					</td>
					<td class="aligncen">
						<div class="empimg">
							<% if emp.current_status == 1 %>
								<img src="/assets/online-icon.png" data-toggle="tooltip" title="Online">
							<% else %>
								<img src="/assets/offline-icon.png" data-toggle="tooltip" title="Offline">
							<% end %>
						</div>
					</td>
					<td class="aligncen">
						<a href="/ve/<%= emp.id %>" data-toggle="tooltip" title="View" data-remote="true"><i class="fa fa-eye"></i></a>
					</td>
					<td class="aligncen">
						<a href="/eepd/<%= emp.id %>" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a>
					</td>
					<td class="aligncen">
						<a href="javascript:void()" data-toggle="tooltip" title="Remove" onclick="deleteemp(<%= emp.id %>)"><i class="fa fa-trash-o"></i></a>
					</td>
				</tr>
				<% i += 1%>
			<% end %>
		</tbody>
	<% else %>
		<tbody>
			<tr style="color:#E25336;">
				<td colspan="10" class="aligncen">
					<b><i class="fa fa-warning" style="color:#E25336;"></i>&emsp;No Employees found!</b>
				</td>
			</tr>
		</tbody>
	<% end %>
</table>

app/views/admin/_view_employee.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Employee Details</h5>
			</div>

			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<table class="table table-hover">
							<tr>
								<td>Employee ID</td>
								<td>:&emsp;<%= @emp.empid %></td>
							</tr>
							<tr>
								<td>Name</td>
								<td>:&emsp;<%= @emp.name %></td>
							</tr>
							<tr>
								<td>Email</td>
								<td>:&emsp;<%= @emp.email %></td>
							</tr>
							<tr>
								<td>Phone Number</td>
								<td>:&emsp;<%= @empdetail.phone_no %></td>
							</tr>
							<tr>
								<td>Address</td>
								<td>:&emsp;<%= @empdetail.door_no %>, <%= @empdetail.street %>, <%= @empdetail.village %>, <%= @empdetail.city %> - <%= @empdetail.pincode %></td>
							</tr>
							<tr>
								<td>Educational Qualification</td>
								<td>:&emsp;<%= QualificationMaster.find(@empdetail.qualification).name %></td>
							</tr>
							<tr>
								<td>Department</td>
								<td>:&emsp;<%= DepartmentMaster.find(@empdetail.department).name %></td>
							</tr>
							<tr>
								<td>Years of Experience</td>
								<td>:&emsp;<%= @empdetail.experience %></td>
							</tr>
							<tr>
								<td>Date of Birth</td>
								<td>:&emsp;<%= @empdetail.birth_date.strftime('%d-%b-%Y') %></td>
							</tr>
							<tr>
								<td>Bank Account Number</td>
								<td>:&emsp;<%= @empdetail.bank_acc_no %></td>
							</tr>
							<tr>
								<td>Bank IFSC Code</td>
								<td>:&emsp;<%= @empdetail.bank_ifsc %></td>
							</tr>
						</table>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/admin/add_new_career.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.cares').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h5 class="page-title">Careers</h5>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header"><div class="card-title">Add New Career</div></div>
							<div class="card-body">
								<%= form_tag("/create_career", method: "post") do %>
									<div class="col-md-6">
										<div class="form-group">
											<label for="name">Name</label>
											<input type="text" name="name" class="form-control form-control-lg" required>
										</div>
									</div>

									<div class="col-md-12">
										<div class="form-group">
											<label for="description">Description</label>
											<textarea name="description" rows="3" class="form-control" required></textarea>
										</div>

										<div class="form-group">
											<label for="skill">Skills</label>
											<span style="color:#E25336;">&emsp;(Each point starting with '@')</span>
											<textarea name="skill" rows="5" class="form-control" required></textarea>
										</div>
									</div>

									<div class="col-md-12">
										<div class="form-group">
											<input type="submit" name="submit" value="Submit" class="btn btn-app pull-right">
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/admin/check_contact.html.erb
<!DOCTYPE html>
<html>
<head></head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Mailbox</h4>
				<div class="row">
					<div class="col-md-12">
						<div class="card card-tasks">
							<div class="card-header ">
								<h4 class="card-title">Contact Us Mail</h4>
							</div>
							<div class="card-body">
								<div class="table-full-width">
									<table class="table">
										<thead>
											<tr>
												<th>
													<input type="checkbox" name="">
												</th>
												<th>Name</th>
												<th>Message</th>
												<th>Date</th>
											</tr>
										</thead>

										<tbody>
											<% if @contacts %>
												<% @contacts.each do |c| %>
													<tr>
														<td><input type="checkbox" name=""></td>
														<td><%= c.name %></td>
														<td><%= c.message %></td>
														<td><%= c.contact_date.strftime('%d-%m-%Y') %></td>
														<td class="td-actions text-right">
															<div class="form-button-action">
																<button type="button" data-toggle="tooltip" title="Edit Task" class="btn btn-link <btn-simple-primary">
																	<i class="fa fa-edit"></i>
																</button>
																<button type="button" data-toggle="tooltip" title="Remove" class="btn btn-link btn-simple-danger">
																	<i class="fa fa-times"></i>
																</button>
															</div>
														</td>
													</tr>
												<% end %>
												
											<% else %>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

app/views/admin/edit_career.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.cares').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h5 class="page-title">Careers</h5>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header"><div class="card-title">Add New Career</div></div>
							<div class="card-body">
								<%= form_tag("/uc/#{params[:id]}", method: "post") do %>
									<div class="col-md-6">
										<div class="form-group">
											<label for="name">Name</label>
											<% if params[:edit].to_i == 1 %>
												<input type="text" name="name" class="form-control form-control-lg" value="<%= @editc.name %>" required>
											<% elsif params[:view].to_i == 1 %>
												<input type="text" name="name" class="form-control form-control-lg" value="<%= @editc.name %>" disabled>
											<% end %>
										</div>
									</div>

									<div class="col-md-12">
										<div class="form-group">
											<label for="description">Description</label>
											<% if params[:edit].to_i == 1 %>
												<textarea name="description" rows="3" class="form-control" required><%= @editc.description %></textarea>
											<% elsif params[:view].to_i == 1 %>
												<textarea name="description" rows="3" class="form-control" required disabled><%= @editc.description %></textarea>
											<% end %>
										</div>

										<div class="form-group">
											<label for="skill">Skills</label>
											<span style="color:#E25336;">&emsp;(Give each point starting with '@')</span>
											<% if params[:edit].to_i == 1 %>
												<textarea name="skill" rows="5" class="form-control" required><%= @editc.skills %></textarea>
											<% elsif params[:view].to_i == 1 %>
												<textarea name="skill" rows="5" class="form-control" required disabled><%= @editc.skills %></textarea>
											<% end %>
										</div>
									</div>

									<div class="col-md-12">
										<div class="form-group">
											<a href="/careers" class="btn btn-cancel">Cancel</a>
											<% if params[:edit].to_i == 1 %>
												<input type="submit" name="submit" value="Update" class="btn btn-app pull-right">
											<% end %>
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/admin/emp_profile.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.emps').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Employees Details</h4>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Employees Personal Details</div>
							</div>
							<div class="card-body">
								<%= form_tag create_emp_detail_path(params[:id]) do %>
									<div class="col-md-6 pull-left">
										<div class="form-group">
											<label>Door No</label>
											<input name="door_no" class="form-control" placeholder="Door no" autofocus="on" required>
										</div>
										<div class="form-group">
											<label>Street Name</label>
											<input name="street" class="form-control caplet" placeholder="Street" required>
										</div>
										<div class="form-group">
											<label>Village / Post</label>
											<input name="post" class="form-control caplet" placeholder="Village / Hometown" required>
										</div>
										<div class="form-group">
											<label>City</label>
											<input name="city" class="form-control caplet" placeholder="City" required>
										</div>
										<div class="form-group">
											<label>Pincode</label>
											<input name="pincode" class="form-control numeric" placeholder="Pincode" required>
										</div>
										<div class="form-group">
											<label>Experience</label>
											<input name="expri" class="form-control numeric" placeholder="Experience" required>
										</div>
									</div>

									<div class="col-md-6 pull-right">
										<div class="form-group">
											<label>Educational Qualification</label>
											<select name="degree" class="form-control" required>
												<option value="0">Please Select</option>
												<% @qualies.each do |q| %>
													<option value="<%= q.id %>"><%= q.name %></option>
												<% end %>
											</select>
										</div>
										<div class="form-group">
											<label>Department</label>
											<select name="dept" class="form-control" required>
												<option value="0">Select</option>
												<%= @departs.each do |d| %>
													<option value="<%= d.id %>"><%= d.name %></option>
												<% end %>
											</select>
										</div>
										<div class="form-group">
											<label>Mobile Number</label>
											<input name="mobile" class="form-control numeric" placeholder="Mobile Number" maxlength="10" required>
										</div>
										<div class="form-group">
											<label>Date of Birth</label>
											<input type="text" name="birth" id="date" class="form-control" placeholder="dd-mm-yyyy" required>
										</div>
										<div class="form-group">
											<label>Bank Account Number</label>
											<input name="accno" class="form-control numeric" placeholder="Account Number" required>
										</div>
										<div class="form-group">
											<label>Bank IFSC Code</label>
											<input name="ifsc" class="form-control uplet" placeholder="IFSC Code" required>
										</div>
									</div>

									<div style="margin-top:1em;">&emsp;</div>
									<div class="col-md-12">
										<div class="form-group">
											<input type="submit" name="submit" value="Submit" class="btn btn-app pull-right">
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/admin/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.home').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h4 class="page-title">Dashboard</h4>
				<div class="row">
					<div class="col-md-3">
						<div class="card card-stats card-warning">
							<div class="card-body ">
								<div class="row">
									<div class="col-5">
										<div class="icon-big text-center">
											<i class="fa fa-users"></i>
										</div>
									</div>
									<div class="col-7 d-flex align-items-center">
										<div class="numbers">
											<p class="card-category">Contact Us</p>
											<h4 class="card-title"><%= @contacts.count %></h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="card card-stats card-info">
							<div class="card-body ">
								<div class="row">
									<div class="col-5">
										<div class="icon-big text-center">
											<i class="fa fa-users"></i>
										</div>
									</div>
									<div class="col-7 d-flex align-items-center">
										<div class="numbers">
											<p class="card-category">Job Applied</p>
											<h4 class="card-title"><%= @careers.count %></h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="card card-stats card-danger">
							<div class="card-body ">
								<div class="row">
									<div class="col-5">
										<div class="icon-big text-center">
											<i class="fa fa-users"></i>
										</div>
									</div>
									<div class="col-7 d-flex align-items-center">
										<div class="numbers">
											<p class="card-category">Total Employees</p>
											<h4 class="card-title"><%= @employees.count %></h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="card card-stats card-primary">
							<div class="card-body ">
								<div class="row">
									<div class="col-5">
										<div class="icon-big text-center">
											<i class="fa fa-users"></i>
										</div>
									</div>
									<div class="col-7 d-flex align-items-center">
										<div class="numbers">
											<p class="card-category">Today Presents</p>
											<h4 class="card-title">1,294</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="card card-tasks">
							<div class="card-header ">
								<h4 class="card-title">Job Applications</h4>
							</div>
							<div class="card-body">
								<div class="table-full-width">
									<table class="table">
										<thead>
											<tr>
												<th>
													<input type="checkbox" name="">
												</th>
												<th>Name</th>
												<th>Email</th>
												<th>Phone Number</th>
												<th>Position</th>
												<th>Profile</th>
												<th>Delete</th>
											</tr>
										</thead>

										<tbody>
											<% if @careers %>
												<% @careers.each do |c| %>
													<tr class="text-center">
														<td><input type="checkbox" name=""></td>
														<td><%= c.name %></td>
														<td><%= c.email %></td>
														<td><%= c.phone_no %></td>
														<td><%= Career.find(c.applied_for).name %></td>
														<td><a href="<%= c.resume_link %>" data-toggle="tooltip" title="View Profile" target="_blank"><i class="fa fa-eye"></i></a></td>
														<td class="td-actions">
															<div class="form-button-action">
																<button type="button" data-toggle="tooltip" title="Remove" class="btn btn-link btn-simple-danger">
																	<i class="fa fa-times"></i>
																</button>
															</div>
														</td>
													</tr>
												<% end %>
												
											<% else %>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>

				
			</div>
		</div>
	</div>
</body>
</html>

app/views/admin/new_employee.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		$(document).ready(function(){
			$('ul.nav li.nav-item.emps').addClass('active');
		});
	</script>
</head>

<body>
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<h5 class="page-title">Employees</h5>
				<div class="row">
					<div class="col-md-3">&nbsp;</div>
					<div class="col-md-6">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Create New Employee</div>
							</div>
							<div class="card-body">
								<%= form_tag("/newemp", method: "post") do %>
									<div class="form-group">
										<input type="text" name="empid" autofocus="true" placeholder="Employee ID" class="form-control checkempid numeric" required />
									</div>
									<div class="form-group">
										<input type="text" name="name" placeholder="Name" class="form-control caplet" required />
									</div>
									<div class="form-group">
								  	<input type="email" name="email" placeholder="E-mail" class="form-control" required />
									</div>
									<div class="form-group">
								  	<input type="password" name="password" placeholder="Password" class="form-control" required />
									</div>
									<div class="form-group">
								  	<input type="password" name="password_confirmation" placeholder="Password again" class="form-control" required />
									</div>
									<div class="form-group">
										<a href="/emps" class="btn btn-default pull-left">Cancel</a>
								  	<input type="submit" value="Next" class="btn btn-app pull-right" />
									</div>
								<% end %>
							</div>
						</div>
					</div>
					<div class="col-md-3">&nbsp;</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/admin/view_employee.js.erb
$('<%= j render "view_employee" %>').modal();